### PR TITLE
Capstone chogum

### PR DESCRIPTION
**Pull request by TuyishimireEric**
# Capstone-Project-CHOGM-2022
|This is a Capstone CHOGM meeting website

the 20th June 2022 - 25th June 2022, the Commonwealth Heads Of Government Meeting (CHOGM) took place in Rwanda, In this project, I have created a website that can be used in CHOGM meetings to inform and gives information about the meeting.

I have created this project with JavaScript, HTML, and CSS

> [Project Description video](https://www.loom.com/share/7a1967c2ee434577976b3227da7bdabd)

### CODE REVIEW

**Review by keneogu — CHANGES_REQUESTED** [review]
Hi @TuyishimireEric, 

Good job so far!

- All linters are passing
- You are following GitHub flow
- Nice design
- Good commit history

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x] The about page background is not the same as the front page. it has a dark background. please fix this.
- [ ] In the mobile version, increase the font size, it should be similar to the given design.

_Check the comments under the review._

## Optional suggestions

- [ ] Your logo is stretched you can make look good as the same from your video. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TuyishimireEric** [comment]
Thank you Mr. @keneogu for reviewing my project, 
Thank you for your motivating feedback too I really appreciate

I think it will be better for me to make some changes if I get the clear explanations on  ***" The about page background is not the same as the front page. it has a dark background. please fix this."***  as suggested

**Comment by keneogu** [comment]
> 

If you look at the about page design on the given design you will notice it doesn't have the image background like the home page. you can check it on the mobile version, its clearer.

**Comment by TuyishimireEric** [comment]
Thank you @keneogu, I have now understood what to do.

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @TuyishimireEric,

✔️ Awesome design
✔️ Responsiveness

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
